import pandas as pd
from datetime import datetime

print("="*80)
print("GENERANDO SCRIPT SQL DE VALIDACION PREVIA")
print("="*80)
print()

# Cargar datos
df_alta = pd.read_excel('datos_generados/revision_grupos_alta_confianza_completo.xlsx')

print(f"Total de locations a consolidar: {len(df_alta)}")
print(f"Total de grupos: {df_alta['Grupo ID'].nunique()}")
print(f"Masters: {df_alta['Es Master'].sum()}")
print(f"Duplicados: {(df_alta['Es Master'] == False).sum()}")
print()

# Preparar IDs
master_ids = df_alta[df_alta['Es Master'] == True]['Location ID'].astype(int).tolist()
duplicado_ids = df_alta[df_alta['Es Master'] == False]['Location ID'].astype(int).tolist()

# Generar script de validación
validation_file = f'datos_generados/00_validacion_previa_consolidacion_{datetime.now().strftime("%Y%m%d_%H%M%S")}.sql'

with open(validation_file, 'w', encoding='utf-8') as f:
    f.write("-- ============================================================================\n")
    f.write("-- SCRIPT DE VALIDACION PREVIA A LA CONSOLIDACION\n")
    f.write(f"-- Generado: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    f.write("-- ============================================================================\n")
    f.write("-- IMPORTANTE: Ejecutar este script ANTES del script de consolidacion\n")
    f.write("-- para verificar el estado de la base de datos y detectar posibles problemas.\n")
    f.write("-- ============================================================================\n\n")

    f.write("SET @masters_count = " + str(len(master_ids)) + ";\n")
    f.write("SET @duplicados_count = " + str(len(duplicado_ids)) + ";\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- 1. ESTADO ACTUAL DE LA BASE DE DATOS\n")
    f.write("-- ============================================================================\n\n")

    f.write("SELECT '=== ESTADO ACTUAL ===' as Seccion;\n\n")

    f.write("-- Total de locations activas\n")
    f.write("SELECT \n")
    f.write("    'Locations activas (no deleted)' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Baseline antes de consolidacion' as Nota\n")
    f.write("FROM CustomerLocation\n")
    f.write("WHERE Deleted IS NULL OR Deleted = 0;\n\n")

    f.write("-- Total de pedidos activos\n")
    f.write("SELECT \n")
    f.write("    'Pedidos activos' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Se van a redistribuir a masters' as Nota\n")
    f.write("FROM orders\n")
    f.write("WHERE Deleted IS NULL OR Deleted = 0;\n\n")

    f.write("-- Total de codigos logisticos activos\n")
    f.write("SELECT \n")
    f.write("    'Codigos logisticos activos' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Se van a mover o marcar deleted' as Nota\n")
    f.write("FROM LogisticCode\n")
    f.write("WHERE Deleted IS NULL OR Deleted = 0;\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- 2. VERIFICACION DE LOCATIONS A CONSOLIDAR\n")
    f.write("-- ============================================================================\n\n")

    f.write("SELECT '=== VERIFICACION DE LOCATIONS ===' as Seccion;\n\n")

    # Generar lista de IDs para verificar
    masters_str = ','.join(map(str, master_ids[:100]))  # Primeros 100
    duplicados_str = ','.join(map(str, duplicado_ids[:100]))  # Primeros 100

    f.write("-- Verificar que los masters existen y no estan deleted\n")
    f.write("SELECT \n")
    f.write("    'Masters que existen y estan activos' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    CONCAT('Esperado: ', @masters_count) as Esperado\n")
    f.write("FROM CustomerLocation\n")
    f.write(f"WHERE ID IN ({masters_str})\n")
    f.write("  AND (Deleted IS NULL OR Deleted = 0);\n\n")

    f.write("-- Verificar masters que NO existen o estan deleted (PROBLEMA)\n")
    f.write("SELECT \n")
    f.write("    'Masters con problemas (deleted o no existen)' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Esperado: 0 - Si > 0 revisar antes de consolidar' as Esperado\n")
    f.write("FROM (\n")
    f.write(f"    SELECT {masters_str.split(',')[0]} as ID\n")
    for id in master_ids[1:20]:  # Sample
        f.write(f"    UNION ALL SELECT {id}\n")
    f.write(") masters\n")
    f.write("LEFT JOIN CustomerLocation cl ON masters.ID = cl.ID AND (cl.Deleted IS NULL OR cl.Deleted = 0)\n")
    f.write("WHERE cl.ID IS NULL;\n\n")

    f.write("-- Verificar duplicados que existen y estan activos\n")
    f.write("SELECT \n")
    f.write("    'Duplicados que existen y estan activos' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    CONCAT('Esperado: ', @duplicados_count) as Esperado\n")
    f.write("FROM CustomerLocation\n")
    f.write(f"WHERE ID IN ({duplicados_str})\n")
    f.write("  AND (Deleted IS NULL OR Deleted = 0);\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- 3. ANALISIS DE PEDIDOS\n")
    f.write("-- ============================================================================\n\n")

    f.write("SELECT '=== ANALISIS DE PEDIDOS ===' as Seccion;\n\n")

    f.write("-- Pedidos en locations master\n")
    f.write("SELECT \n")
    f.write("    'Pedidos en masters' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Estos se mantienen en el master' as Nota\n")
    f.write("FROM orders\n")
    f.write(f"WHERE CustomerLocationId IN ({masters_str})\n")
    f.write("  AND (Deleted IS NULL OR Deleted = 0);\n\n")

    f.write("-- Pedidos en locations duplicadas (se van a mover)\n")
    f.write("SELECT \n")
    f.write("    'Pedidos en duplicados' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Se van a mover al master correspondiente' as Nota\n")
    f.write("FROM orders\n")
    f.write(f"WHERE CustomerLocationId IN ({duplicados_str})\n")
    f.write("  AND (Deleted IS NULL OR Deleted = 0);\n\n")

    f.write("-- Verificar pedidos huerfanos (sin CustomerLocation)\n")
    f.write("SELECT \n")
    f.write("    'Pedidos huerfanos (sin location)' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Esperado: 0 - Si > 0 hay un problema de integridad' as Nota\n")
    f.write("FROM orders o\n")
    f.write("LEFT JOIN CustomerLocation cl ON o.CustomerLocationId = cl.ID\n")
    f.write("WHERE cl.ID IS NULL\n")
    f.write("  AND (o.Deleted IS NULL OR o.Deleted = 0);\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- 4. ANALISIS DE CODIGOS LOGISTICOS\n")
    f.write("-- ============================================================================\n\n")

    f.write("SELECT '=== ANALISIS DE CODIGOS LOGISTICOS ===' as Seccion;\n\n")

    f.write("-- Codigos en masters\n")
    f.write("SELECT \n")
    f.write("    'Codigos logisticos en masters' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Base actual de codigos en masters' as Nota\n")
    f.write("FROM LogisticCode\n")
    f.write(f"WHERE CustomerLocationId IN ({masters_str})\n")
    f.write("  AND (Deleted IS NULL OR Deleted = 0);\n\n")

    f.write("-- Codigos en duplicados\n")
    f.write("SELECT \n")
    f.write("    'Codigos logisticos en duplicados' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Se intentaran mover al master (o marcar deleted si duplicados)' as Nota\n")
    f.write("FROM LogisticCode\n")
    f.write(f"WHERE CustomerLocationId IN ({duplicados_str})\n")
    f.write("  AND (Deleted IS NULL OR Deleted = 0);\n\n")

    f.write("-- Detectar conflictos potenciales de codigos\n")
    f.write("-- (mismo distributor + code en master y duplicado)\n")
    f.write("SELECT \n")
    f.write("    'Codigos duplicados que generaran conflictos' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Estos se marcaran como deleted automaticamente' as Nota\n")
    f.write("FROM LogisticCode lc_dup\n")
    f.write(f"WHERE lc_dup.CustomerLocationId IN ({duplicados_str})\n")
    f.write("  AND (lc_dup.Deleted IS NULL OR lc_dup.Deleted = 0)\n")
    f.write("  AND EXISTS (\n")
    f.write("    SELECT 1 FROM LogisticCode lc_master\n")
    f.write(f"    WHERE lc_master.CustomerLocationId IN ({masters_str})\n")
    f.write("      AND lc_master.MarketplaceDistributorId = lc_dup.MarketplaceDistributorId\n")
    f.write("      AND lc_master.Code = lc_dup.Code\n")
    f.write("      AND (lc_master.Deleted IS NULL OR lc_master.Deleted = 0)\n")
    f.write("  );\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- 5. VERIFICACION DE INTEGRIDAD REFERENCIAL\n")
    f.write("-- ============================================================================\n\n")

    f.write("SELECT '=== INTEGRIDAD REFERENCIAL ===' as Seccion;\n\n")

    f.write("-- Verificar que no hay referencias circulares o problemas\n")
    f.write("SELECT \n")
    f.write("    'Locations que son master Y duplicado' as Problema,\n")
    f.write("    COUNT(*) as Cantidad,\n")
    f.write("    'Esperado: 0 - CRITICO si > 0' as Nota\n")
    f.write("FROM (\n")
    f.write(f"    SELECT ID FROM CustomerLocation WHERE ID IN ({masters_str})\n")
    f.write("    INTERSECT\n")
    f.write(f"    SELECT ID FROM CustomerLocation WHERE ID IN ({duplicados_str})\n")
    f.write(") conflictos;\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- 6. ANALISIS DE IMPACTO\n")
    f.write("-- ============================================================================\n\n")

    f.write("SELECT '=== IMPACTO DE LA CONSOLIDACION ===' as Seccion;\n\n")

    f.write("-- Resumen de impacto\n")
    f.write("SELECT \n")
    f.write("    'Locations activas ANTES' as Metrica,\n")
    f.write("    COUNT(*) as Cantidad\n")
    f.write("FROM CustomerLocation\n")
    f.write("WHERE Deleted IS NULL OR Deleted = 0\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    'Locations que se marcaran deleted',\n")
    f.write("    @duplicados_count\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    'Locations activas DESPUES (estimado)',\n")
    f.write("    COUNT(*) - @duplicados_count\n")
    f.write("FROM CustomerLocation\n")
    f.write("WHERE Deleted IS NULL OR Deleted = 0\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    'Reduccion en locations',\n")
    f.write("    @duplicados_count\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    'Porcentaje de reduccion',\n")
    f.write("    ROUND((@duplicados_count * 100.0 / COUNT(*)), 2)\n")
    f.write("FROM CustomerLocation\n")
    f.write("WHERE Deleted IS NULL OR Deleted = 0;\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- 7. VERIFICACION DE TABLAS DE BACKUP\n")
    f.write("-- ============================================================================\n\n")

    f.write("SELECT '=== VERIFICACION DE ESPACIO Y BACKUPS ===' as Seccion;\n\n")

    f.write("-- Verificar que no existan backups previos (evitar conflictos)\n")
    f.write("SELECT \n")
    f.write("    'Tabla' as Tabla,\n")
    f.write("    CASE \n")
    f.write(f"        WHEN COUNT(*) > 0 THEN 'YA EXISTE - Renombrar o eliminar antes de ejecutar'\n")
    f.write("        ELSE 'OK - No existe'\n")
    f.write("    END as Estado\n")
    f.write("FROM information_schema.tables\n")
    f.write(f"WHERE table_name = 'CustomerLocation_Backup_{datetime.now().strftime('%Y%m%d')}'\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    'orders_Backup',\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) > 0 THEN 'YA EXISTE - Renombrar o eliminar antes de ejecutar'\n")
    f.write("        ELSE 'OK - No existe'\n")
    f.write("    END\n")
    f.write("FROM information_schema.tables\n")
    f.write(f"WHERE table_name = 'orders_Backup_{datetime.now().strftime('%Y%m%d')}'\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    'LogisticCode_Backup',\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) > 0 THEN 'YA EXISTE - Renombrar o eliminar antes de ejecutar'\n")
    f.write("        ELSE 'OK - No existe'\n")
    f.write("    END\n")
    f.write("FROM information_schema.tables\n")
    f.write(f"WHERE table_name = 'LogisticCode_Backup_{datetime.now().strftime('%Y%m%d')}';\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- 8. CHECKLIST FINAL\n")
    f.write("-- ============================================================================\n\n")

    f.write("SELECT '=== CHECKLIST FINAL ===' as Seccion;\n\n")

    f.write("SELECT \n")
    f.write("    'Checklist Item' as Item,\n")
    f.write("    'Estado' as Estado,\n")
    f.write("    'Accion Requerida' as Accion\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    '1. Todos los masters existen y estan activos',\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) = @masters_count THEN 'OK'\n")
    f.write("        ELSE 'ERROR'\n")
    f.write("    END,\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) = @masters_count THEN 'Ninguna'\n")
    f.write("        ELSE 'Verificar masters faltantes o deleted'\n")
    f.write("    END\n")
    f.write("FROM CustomerLocation\n")
    f.write(f"WHERE ID IN ({masters_str})\n")
    f.write("  AND (Deleted IS NULL OR Deleted = 0)\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    '2. Todos los duplicados existen y estan activos',\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) = @duplicados_count THEN 'OK'\n")
    f.write("        ELSE 'REVISAR'\n")
    f.write("    END,\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) = @duplicados_count THEN 'Ninguna'\n")
    f.write("        ELSE 'Algunos duplicados ya fueron deleted - revisar'\n")
    f.write("    END\n")
    f.write("FROM CustomerLocation\n")
    f.write(f"WHERE ID IN ({duplicados_str})\n")
    f.write("  AND (Deleted IS NULL OR Deleted = 0)\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    '3. No hay pedidos huerfanos',\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) = 0 THEN 'OK'\n")
    f.write("        ELSE 'ERROR'\n")
    f.write("    END,\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) = 0 THEN 'Ninguna'\n")
    f.write("        ELSE 'Corregir integridad referencial antes de continuar'\n")
    f.write("    END\n")
    f.write("FROM orders o\n")
    f.write("LEFT JOIN CustomerLocation cl ON o.CustomerLocationId = cl.ID\n")
    f.write("WHERE cl.ID IS NULL\n")
    f.write("  AND (o.Deleted IS NULL OR o.Deleted = 0)\n")
    f.write("UNION ALL\n")
    f.write("SELECT \n")
    f.write("    '4. Tablas de backup no existen',\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) = 0 THEN 'OK'\n")
    f.write("        ELSE 'ADVERTENCIA'\n")
    f.write("    END,\n")
    f.write("    CASE \n")
    f.write("        WHEN COUNT(*) = 0 THEN 'Ninguna'\n")
    f.write("        ELSE 'Renombrar o eliminar backups existentes'\n")
    f.write("    END\n")
    f.write("FROM information_schema.tables\n")
    f.write(f"WHERE table_name IN ('CustomerLocation_Backup_{datetime.now().strftime('%Y%m%d')}', 'orders_Backup_{datetime.now().strftime('%Y%m%d')}', 'LogisticCode_Backup_{datetime.now().strftime('%Y%m%d')}');\n\n")

    f.write("-- ============================================================================\n")
    f.write("-- FIN DEL SCRIPT DE VALIDACION\n")
    f.write("-- ============================================================================\n")
    f.write("--\n")
    f.write("-- IMPORTANTE: Revisar todos los resultados antes de ejecutar el script\n")
    f.write("-- de consolidacion. Si hay errores o advertencias, corregirlos primero.\n")
    f.write("--\n")
    f.write("-- Si todos los checks muestran 'OK', es seguro proceder con:\n")
    f.write("-- 01_consolidar_alta_confianza_YYYYMMDD_HHMMSS.sql\n")
    f.write("-- ============================================================================\n")

print(f"Script de validacion generado: {validation_file}")
print()
print("="*80)
print("SCRIPT DE VALIDACION GENERADO EXITOSAMENTE")
print("="*80)
print()
print(f"Archivo: {validation_file}")
print()
print("CONTENIDO DEL SCRIPT:")
print("  1. Estado actual de la BD (locations, pedidos, codigos)")
print("  2. Verificacion de locations a consolidar")
print("  3. Analisis de pedidos")
print("  4. Analisis de codigos logisticos")
print("  5. Verificacion de integridad referencial")
print("  6. Analisis de impacto")
print("  7. Verificacion de espacio y backups")
print("  8. Checklist final con GO/NO-GO")
print()
print("USAR ANTES DE EJECUTAR LA CONSOLIDACION")
print()
